version: "3.1"
services:
  frontend:
    container_name: frontend
    build:
      context: ../fe
      dockerfile: ../infra/images/fe.Dockerfile
    restart: unless-stopped
    ports:
      - 4500:4500

  backend:
    container_name: backend
    build:
      context: ../be
      dockerfile: ../infra/images/be.Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000